#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"


SCREEN_PASS_TEXTURE_VIEWPORT(ViewPort)

Texture2D<float4> InColorTexture; // In RGB
Texture2D<float4> InEdgesTexture;

SamplerState sampler0;

float4 CombineEdgesPS(
	float2 InUV : TEXCOORD0
) : SV_Target0
{
	float3 ColorRGB = InColorTexture.Sample(sampler0, InUV).rgb;

	float EdgesVal = InEdgesTexture.Sample(sampler0, InUV).r;

	return float4((ColorRGB * EdgesVal), 1.0f);
}
